### ISSUE TITLE
dev-validate.py broken: passes str model instead of JujuModelHandle after #842 refactor

### ISSUE THREAD

**Issue by dmvdm** [canonical/charm-integration-testing#916]
## Summary

`development-sandbox/bin/dev-validate.py` is broken for any invocation and always
crashes with:

```
AttributeError: 'str' object has no attribute 'uri'
```

## Root cause

PR #842 (`98036a6`, "refactor: replace `model: str` with explicit
`JujuModelHandle(controller, model)`") changed every backend/extension method's
`model` parameter from a plain string to a `JujuModelHandle(controller=..., model=...)`
dataclass (which exposes a `.uri` property used internally, e.g. in
`JubilantClient.model()` and `JubilantBackend.is_k8s_model()`).

That PR touched 57 files across `charm_integration_testing/` (backends, extensions,
test_suite, and their unit tests) but **missed
`development-sandbox/bin/dev-validate.py`**, which still does:

```python
parser.add_argument("--model", default="testing", ...)
...
is_k8s = backend.is_k8s_model(args.model)          # args.model is a bare str
...
results = extension.post_validate(args.model, args.app, args.level)  # same issue
```

Both call sites (the `--reinstall` path and the normal `post_validate` path) pass the
raw string straight through to code that now unconditionally does `model.uri`,
so the script fails immediately regardless of the flags used.

## Steps to reproduce

```bash
python3 development-sandbox/bin/dev-validate.py --model <any-model> --app <any-app> --level simple
```

## Actual result

```
Traceback (most recent call last):
  File "development-sandbox/bin/dev-validate.py", line 118, in main
    results = extension.post_validate(args.model, args.app, args.level)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "charm_integration_testing/extensions/validator_injection/extension.py", line 51, in post_validate
    model_is_k8s = self.juju.is_k8s_model(model)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "charm_integration_testing/juju_jubilant/backend.py", line 712, in is_k8s_model
    return self.client.model(model).show_model().type == "kubernetes"
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "charm_integration_testing/juju_jubilant/client.py", line 14, in model
    model=model.uri if model is not None else None,
          ^^^^^^^^^
AttributeError: 'str' object has no attribute 'uri'
```

## Expected result

The script injects/runs validators against the given model+app as before the
refactor, without crashing.

## Suggested fix

Add a `--controller` option (or resolve the current/active controller) to
`dev-validate.py` and construct a `JujuModelHandle(controller=..., model=args.model)`
before passing it to `JubilantBackend`/`ValidatorInjectorExtension`, mirroring the
pattern already used throughout `charm_integration_testing/test_suite/*.py` after #842.

## Impact

This script is the primary local dev-loop tool documented by the `test-validator` and
`develop-validator` skills for manually exercising a validator against a live
deployment (`$PROJECT_ROOT/development-sandbox/bin/dev-validate.py`). It has been
non-functional for any real use since #842 merged (2026-08-27).
